export const state = () => ({
  menu: [
    {
      type: "link",
      label: "Home",
      to: "/",
      icon: "home",
      group: "*",
      section: "*",
      user_id: "*",
    },
    {
      label: "Sample Reg",
      type: "group",
      icon: "assignment",
      group: "BCEFG",
      section: "*",
      user_id: "*",
      links: [
        {
          label: "Client Notes",
          type: "link",
          icon: "assignment",
          to: "/registration/clients/notes",
          group: "BCEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Label Printing",
          type: "link",
          icon: "print",
          to: "/registration/labels",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Job Release",
          type: "link",
          icon: "mdi-beaker-check",
          to: "/registration/job_release",
          group: "BCEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "AGS",
          type: "group",
          group: "BCEFG",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "AGS Convertor",
              icon: "list",
              to: "/registration/ags",
              group: "BCEFG",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "Projects",
          type: "group",
          group: "J",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Projects List",
              icon: "list",
              to: "/registration/projects",
              group: "J",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "Unscheduled Samples",
          type: "group",
          group: "*",
          section: "BOOKING IN",
          user_id: "*",
          links: [
            {
              label: "Registered Batches",
              icon: "list",
              to: "/registration/unscheduled_batches",
              group: "J",
              section: "*",
              user_id: "*",
            },
            {
              label: "New Batch",
              icon: "add_circle",
              to: "/registration/unscheduled_batches/new",
              group: "*",
              section: "BOOKING IN",
              user_id: "*",
            },
            {
              label: "Export Samples",
              icon: "list",
              to: "/registration/unscheduled_batches/export",
              group: "*",
              section: "BOOKING IN",
              user_id: "*",
            },
          ],
        },
      ],
    },
    {
      label: "Sample Prep",
      type: "group",
      icon: "save_alt",
      group: "BEFGJ",
      section: "PREP, INORGANICS, ORGANICS, BOOKING IN",
      user_id: "*",
      links: [
        {
          label: "Wet Weights / Soil Desc",
          type: "link",
          icon: "mdi-weather-rainy",
          to: "/prep/wet_soil_desc",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Dry Weights",
          type: "link",
          icon: "mdi-weather-sunny",
          to: "/prep/dry_weights",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Soil Splitting",
          type: "link",
          icon: "mdi-pot-outline",
          to: "/prep/soil_splitting",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Water Splitting",
          type: "link",
          icon: "mdi-cup-water",
          to: "/prep/water_splitting",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Phase Two",
          type: "link",
          icon: "mdi-pot-outline",
          to: "/prep/results_entry",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Leachate Prep",
          type: "link",
          icon: "mdi-bottle-wine-outline",
          to: "/prep/leachate",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Rapid Moisture",
          type: "link",
          icon: "mdi-toaster-oven",
          to: "/prep/rapid_moisture",
          group: "BEFGJK",
          section: "*",
          user_id: "*",
        },
        {
          label: "Tray Search",
          type: "link",
          icon: "mdi-card-search-outline",
          to: "/prep/tray_view",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Re-prep",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/prep/reprep",
          group: "*",
          section: "*",
          user_id: "*",
        },
      ],

    },

    {
      label: "Phase One",
      type: "group",
      icon: "reorder",
      group: "*",
      section: "*",
      user_id: "*",
      links: [
        {
          label: "Water Splitting Label",
          type: "group",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Print Splitting Label",
              icon: "print",
              to: "/phase_one/water_splitting_label",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Sample Backlog",
              type: "link",
              icon: "mdi-bottle-wine-outline",
              to: "/phase_one/water_splitting_sample_backlog",
              group: "*",
              section: "*",
              user_id: "*",
            }, 

            {
              label: "Sample Log List",
              type: "link",
              icon: "mdi-bottle-wine-outline",
              to: "/phase_one/water_splitting_sample_log_list",
              group: "*",
              section: "*",
              user_id: "*",
            }, 

            {
              label: "Label Group Setup",
              icon: "settings",
              to: "/phase_one/water_splitting_label_group_setup",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Test Setup",
              icon: "settings",
              to: "/phase_one/water_splitting_test_setup",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Print Bulk Splitting Label",
              icon: "print",
              to: "/phase_one/water_splitting_label_bulk",
              group: "*",
              section: "*",
              user_id: "*",
            },            
          ],
        },

      ],
    },

    
    {
      label: "Organics",
      type: "group",
      icon: "mdi-atom",
      group: "*",
      section: "ORGANICS",
      user_id: "*",
      links: [
        {
          label: "Openlab",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Setup",
              type: "link",
              icon: "assignment",
              to: "/organics/openlab/setup",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "Tenax",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Results",
              type: "link",
              icon: "assignment",
              to: "/organics/tenax",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Compound List",
              type: "link",
              icon: "list",
              to: "/organics/tenax/compounds",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "TPH",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Fuel Type",
              type: "link",
              icon: "assignment",
              to: "/organics/tph/fuel_type",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },


        {
          label: "EPH",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Fuel Type",
              type: "link",
              icon: "assignment",
              to: "/organics/eph/fuel_type",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },


        {
          label: "VPH",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Fuel Type",
              type: "link",
              icon: "assignment",
              to: "/organics/vph/fuel_type",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },


      ],
    },
    {
      label: "Inorganics",
      type: "group",
      icon: "save_alt",
      group: "BDEFGJ",
      section: "INORGANICS",
      user_id: "*",
      links: [
        {
          label: "LOI 440",
          type: "link",
          icon: "mdi-weather-rainy",
          to: "/inorganics/loi_440",
          group: "BDEFGJK",
          section: "*",
          user_id: "*",
        },
      ],
    },


    {
      label: "Laboratory",
      type: "group",
      icon: "assignment",
      group: "*",
      section: "LABORATORY, ORGANICS, INORGANICS , PREP, APPROVER",
      user_id: "*",      
      links: [
    		{
          label: "Sample Check-In",
          type: "link",
          icon: "mdi-bottle-wine-outline",
          to: "/laboratory/sample_check_in",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Sample Check-In List",
          type: "link",
          icon: "mdi-bottle-wine-outline",
          to: "/laboratory/sample_check_in_list",
          group: "*",
          section: "*",
          user_id: "*",
        },     

		],
    },

    {
      label: "Customer Services",
      type: "group",
      icon: "headset_mic",
      group: "*",
      section:
        "CUSTOMER SVC, BOOKING IN, SALES, FINANCE, BID TEAM, ORGANICS, INORGANICS , PREP, APPROVER",
      user_id: "*",
      links: [
        {
          label: "Client Manager",
          type: "link",
          icon: "mdi-card-account-details-outline",
          to: "/customer_services/clients",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Vips",
          type: "link",
          icon: "mdi-account-star",
          to: "/customer_services/vips",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Rush Sample",
          type: "link",
          icon: "mdi-bottle-wine-outline",
          to: "/customer_services/rush_sample",
          group: "*",
          section: "*",
          user_id: "*",
        },        
        {
          label: "Rush Project",
          type: "link",
          icon: "mdi-projector",
          to: "/customer_services/rush_project",
          group: "*",
          section: "*",
          user_id: "*",
        },          
        {
          label: "KeyLab Generator",
          type: "link",
          icon: "mdi-account-star",
          to: "/customer_services/keylab-generator",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Queries",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "New Query",
              type: "link",
              icon: "mdi-account-question",
              to: "/customer_services/queries/new",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "Reporting",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Report Generate",
              type: "link",
              icon: "assignment",
              to: "/customer_services/reporting",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
        {
          label: "Onboarding",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Onboarding List",
              type: "link",
              icon: "assignment",
              to: "/customer_services/onboarding/",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
      ],
    },
  
    {
      label: "Chemsolutions",
      type: "group",
      icon: "mdi-cloud",
      group: "*",
      section: "CUSTOMER SVC, BOOKING IN, PREP, SALES",
      user_id: "*",
      links: [
        {
          label: "COCs",
          type: "link",
          icon: "list",
          to: "/chemsolutions/cocs",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Users",
          type: "link",
          icon: "mdi-account-group",
          to: "/chemsolutions/users",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Barcode Search",
          type: "link",
          icon: "search",
          to: "/chemsolutions/search",
          group: "*",
          section: "*",
          user_id: "*",
        },
      ],
    },
    {
      label: "Bid Team",
      type: "group",
      icon: "mdi-format-list-numbered-rtl",
      group: "*",
      section: "BID TEAM, ACCOUNTS",
      user_id: "*",
      links: [
        {
          label: "Client Price Lists",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/bid_team/clients",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Quotes for eLIMS",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/bid_team/quotes",
          group: "*",
          section: "*",
          user_id: "*",
        },
      ],
    },
    {
      label: "Sales",
      type: "group",
      icon: "mdi-currency-gbp",
      group: "ACFGIJ",
      section: "CUSTOMER SVC,SALES,APPROVER,FINANCE,BID TEAM,TECHNICAL",
      user_id: "*",
      links: [
        {
          label: "Top Client Performance",
          type: "link",
          icon: "mdi-crown",
          to: "/sales/monthly_pr",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Average Selling Price",
          type: "link",
          icon: "mdi-currency-gbp",
          to: "/sales/asp",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Client Trends",
          type: "link",
          icon: "mdi-trending-up",
          to: "/sales/client_trends",
          group: "*",
          section: "*",
          user_id: "*",
        },
        // {
        //   label: 'ASP',
        //   type: 'link',
        //   icon: 'mdi-playlist-check',
        //   to: '/sales/asp',
        //   group: '*',
        //   section: '*',
        //   user_id: '*',
        // },
      ],
    },
    {
      label: "Technical",
      type: "group",
      icon: "ballot",
      group: "FI",
      section: "ORGANICS, INORGANICS, APPROVER, PREP, TECHNICAL, FINANCE",
      user_id: "*",
      links: [
        {
          label: "Approvals",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/technical/approvals",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "AIS Schedule Log",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/technical/ais_schedule_log",
          group: "*",
          section: "*",
          user_id: "*",
        },
      ],
    },
    {
      label: "Operations",
      type: "group",
      icon: "assignment",
      group: "*",
      section: "*",
      user_id: "*",
      links: [
        {
          label: "Pre-bounced",
          type: "link",
          icon: "mdi-playlist-check",
          to: "/technical/pre_bounced",
          group: "*",
          section: "*",
          user_id: "*",
        },         
        {
          label: "Instrumentation",
          type: "group",
          icon: "assignment",
          group: "*",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Inventory",
              type: "link",
              to: "/operations/instrumentation",
              icon: "mdi-calendar-week-begin",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Breakdowns",
              type: "link",
              to: "/operations/instrumentation/breakdowns",
              icon: "mdi-wrench",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Bad Injections",
              type: "link",
              to: "/operations/capacity_model/bad_injections",
              icon: "mdi-wrench",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },
      ],
    },
    {
      label: "Management",
      type: "group",
      icon: "cloud",
      group: "ACEFGIJ",
      section: "*",
      user_id: "*",
      links: [
        {
          label: "Due Jobs",
          type: "link",
          icon: "mdi-clock-time-ten-outline",
          to: "/management/due_jobs",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Due Test Totals",
          type: "link",
          icon: "mdi-test-tube",
          to: "/operations/due_tests",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Hold Samples",
          type: "link",
          icon: "mdi-pause-circle-outline",
          to: "/management/hold_samples",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Prep Stats (NEW)",
          type: "link",
          icon: "mdi-clock-time-ten-outline",
          to: "/management/prep_stats",
          group: "*",
          section: "*",
          user_id: "*",
        },
        {
          label: "Prep Stats (WIP)",
          type: "link",
          icon: "mdi-clock-time-ten-outline",
          to: "/management/prep_stats2",
          group: "*",
          section: "*",
          user_id: "*",
        },

        {
          label: "Dashboards",
          type: "group",
          icon: "assignment",
          group: "ACFGIJ",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Summary",
              type: "link",
              icon: "mdi-monitor-dashboard",
              to: "/management/dashboards/summary",
              group: "*",
              section: "*",
              user_id: "*",
            },
            // {
            //   label: 'Daily Stats',
            //   type: 'link',
            //   icon: 'assignment',
            //   to: '/management/dashboards/daily_stats',
            //   group: '*',
            //   section: '*',
            //   user_id: '*',
            // },
            // {
            //   label: 'Monthly Stats',
            //   type: 'link',
            //   icon: 'assignment',
            //   to: '/management/dashboards/monthly_stats',
            //   group: '*',
            //   section: '*',
            //   user_id: '*',
            // },
            {
              label: "Sample Counts",
              type: "link",
              icon: "assignment",
              to: "/management/dashboards/sample_counts",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Turnaround Times Counts",
              type: "link",
              icon: "assignment",
              to: "/management/dashboards/tat_counts",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Turnaround Times",
              type: "link",
              icon: "mdi-chart-line",
              to: "/management/dashboards/tat",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "TAT-R",
              type: "link",
              icon: "mdi-chart-line",
              to: "/management/dashboards/tatr",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },



        {
          label: "Late Job Report",
          type: "group",
          icon: "assignment",
          group: "ACFGIJ",
          section: "*",
          user_id: "*",
          links: [
            {
              label: "Job Without Subcon",
              type: "link",
              icon: "mdi-monitor-dashboard",
              to: "/management/dashboards/late_report_without_subcon",
              group: "*",
              section: "*",
              user_id: "*",
            },
            {
              label: "Job With Subcon",
              type: "link",
              icon: "mdi-monitor-dashboard",
              to: "/management/dashboards/late_report_with_subcon",
              group: "*",
              section: "*",
              user_id: "*",
            },
          ],
        },




      ],
    },
  ],
});
